// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZByFUhc6vEczG9RjmvxVlnxLd0BO_YYM',
    appId: '1:685006939519:web:29568988d58d2a370fe64a',
    messagingSenderId: '685006939519',
    projectId: 'my-firebase-da1f1',
    authDomain: 'my-firebase-da1f1.firebaseapp.com',
    databaseURL: 'https://my-firebase-da1f1-default-rtdb.firebaseio.com',
    storageBucket: 'my-firebase-da1f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVFIPDBOlbDBrZOIwwukknrGNC4ldpGm0',
    appId: '1:685006939519:android:0ae3d0ac2f4953ec0fe64a',
    messagingSenderId: '685006939519',
    projectId: 'my-firebase-da1f1',
    databaseURL: 'https://my-firebase-da1f1-default-rtdb.firebaseio.com',
    storageBucket: 'my-firebase-da1f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3O7Ft0r6aEva3f_RIIHPrqv2wXVTzjH4',
    appId: '1:685006939519:ios:9e55f199d4e7731d0fe64a',
    messagingSenderId: '685006939519',
    projectId: 'my-firebase-da1f1',
    databaseURL: 'https://my-firebase-da1f1-default-rtdb.firebaseio.com',
    storageBucket: 'my-firebase-da1f1.appspot.com',
    iosBundleId: 'com.example.smartGarden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3O7Ft0r6aEva3f_RIIHPrqv2wXVTzjH4',
    appId: '1:685006939519:ios:8408611b9ba7606b0fe64a',
    messagingSenderId: '685006939519',
    projectId: 'my-firebase-da1f1',
    databaseURL: 'https://my-firebase-da1f1-default-rtdb.firebaseio.com',
    storageBucket: 'my-firebase-da1f1.appspot.com',
    iosBundleId: 'com.example.smartGarden.RunnerTests',
  );
}
